build: add RHEL6 .spec file for packaging
Include the upstream RHEL6 .spec file to ensure the packages we
build match the upstream packages.  Any later patches that change
the packaging should patch the .spec file appropriately.

Signed-off-by: Andreas Dilger <andreas.dilger@intel.com>

diff --git a/contrib/build-rpm b/contrib/build-rpm
--- a/contrib/build-rpm
+++ b/contrib/build-rpm
@@ -34,11 +34,47 @@ EXCLUDE="--exclude .hg* --exclude .pc* --exclude .git*"
 
 [ "`rpmbuild --version 2> /dev/null`" ] && RPM=rpmbuild || RPM=rpm
 
+# which distro and release
+DISTRO=$(lsb_release -is)
+RELEASE=$(lsb_release -rs)
+# now the hacks in case either is empty
+if [ -z "$DISTRO" ]; then
+    echo "You really ought to install the lsb_release binary for this distro"
+    if grep "Fedora " /etc/issue; then
+        DISTRO="Fedora"
+    fi
+fi
+if [ -z "$DISTRO" ]; then
+    echo "Could not determine the distribution.  Please install the lsb_release binary"
+    exit 1
+fi
+if [ -z "$RELEASE" ]; then
+    echo "You really ought to install the lsb_release binary for this distro"
+    case "$DISTRO" in
+        Fedora)
+            RELEASE=$(grep Fedora /etc/issue | sed -e 's/Fedora release //' -e 's/ .*//')
+        ;;
+    esac
+fi
+if [ -z "$RELEASE" ]; then
+    echo "Could not determine the release.  Please install the lsb_release binary"
+    exit 1
+fi
+case "$DISTRO-$RELEASE" in
+    RedHatEnterpriseServer-6*) DISTRO=RHEL; RELEASE=6;;
+    CentOS-6*) DISTRO=RHEL; RELEASE=6;;
+    Fedora-1[234]) DISTRO=RHEL; RELEASE=6;;	# use the same .spec for now
+esac
+
+SPECFILE="$currdir/e2fsprogs-${DISTRO// /_}-$RELEASE.spec"
+if [ ! -f "$SPECFILE" ]; then
+    SPECFILE="$currdir/e2fsprogs.spec"
+fi
 $RPM --define "_sourcedir $tmpdir" \
      --define "_topdir ${RPM_TOPDIR:-$(rpm -E %_topdir)}" \
      --define "_tmpdir ${RPM_TMPDIR:-$TMP}" \
      --define "extra_config_flags ${EXTRA_CONFIG_FLAGS:-''}" \
-     -ba $currdir/e2fsprogs.spec
+     -ba $SPECFILE
 
 rpm_exit=$?
 rm -rf $tmpdir
